### ISSUE TITLE
U-Net segmentation example

### ISSUE THREAD

**Issue by wronk** [developmentseed/label-maker#1]
- [x] Implement vanilla U-net model in Keras (carry simplified code from skynet-deeptrain)
- [ ] Test it
- [ ] .md to show how to train model on google's cloud
- [x] Write simple utility function code to plot a few segmentation predictions

Ideally, run this example on Google's cloud. TPUs (google accelerated hardware) don't look to be ready yet for prime time yet, but I've signed up for alerts

**Comment by crikeli** [comment]
Oooh, I am interested in this too! What are you trying to segment? buildings? TPUs are definitely not ready for prime time, and training models on googles GPUs is not half bad! I'd like to follow your progress since I am planning on implementing a newer version of segmentation using weakly supervised learning. Great project, by the way 👍

**Comment by crikeli** [comment]
@wronk that sounds good! I'd like to run a weakly supervised experiment using label maker, but I would only use label maker to classify satellite patches that have buildings and satellite patches that don't, and then use the concepts described by this paper https://research.fb.com/wp-content/uploads/2016/12/feeback-neural-network.pdf? to perform segmentation. You may want to look into it too for later, since this paper proposes better results than u-net!

- On a side note, I tried to download images via label-maker and I included my map-box access key as an environment variable. The commands ran great, but when I tried to preview the downloaded images, the file was rendered un-openable for some reason. I used the same config.json described in the example for Tanzania. Would appreciate any leads! I'm guessing it has to do with permissions on my access key?

Thanks in advance!

**Comment by Geoyi** [comment]
@crikeli The facebook paper is pretty interesting, thanks for sharing with us and will definitely look into it.  I've not personally tried Tanzania yet but found Mapbox has higher satellite for Vietnam, you could have a try using this [walkthrough](https://github.com/developmentseed/label-maker/blob/master/examples/walkthrough-classification-mxnet-sagemaker.md). You might wanna see [this issue](https://github.com/developmentseed/label-maker/issues/22) about the label maker downloads tiles that could not be opened. Not sure if I have answered your questions. Let us know ~

**Comment by Geoyi** [comment]
#22

**Comment by crikeli** [comment]
Glad you find it interesting! If I'm able to work it out, I may submit a pull request for it. I will give the Vietnam walkthrough a go, thanks!  The issue you referenced seems similar to mine so will look into it! You definitely answered my questions 💯

**Comment by crikeli** [comment]
@Geoyi unfortunately I still am not able to preview my images. Every command runs and does what it's supposed to, but I'm unable to preview my images. I checked that upon running label-maker download and lable-maker labels, I have the necessary labels.npz file and the classification.geojson file. I am further able to confirm the validity of that file by viewing the file on geojson.io. 

- On a side note, I am running label maker on a remote linux machine with the latest tippecanoe and python 3.6.4. I tried running it on my local machine too (mac) but to no avail. Do you have a specific config.json file that has worked for you? Also, are there specific permissions I need to enable on my mapbox access token, or is it supposed to work right out of the box?

Thanks!

**Comment by wronk** [comment]
Hey @crikeli, if you're still having problems, try deleting the entire `/data` folder and re-running all the commands. Also, does running `label-maker images` create the `/tiles` folder with good satellite imagery? If your api key works as far as correctly downloading the imagery in other countries (and you've double checked that it's copied correctly to your other `config.json`), then I doubt that's the problem.

If you're still having problems after that, I'd post a separate issue ticket with a step-by-step of what you've tried.

**Comment by crikeli** [comment]
@wronk , yes, unfortunately I tried deleting the data folder, reinstalling label-maker+dependencies in a clean environment, and literally every single command runs flawlessly, and `label-maker images` does create the `/tiles` folder, but all the images(at least all the ones I tried opening) appear to be corrupted for some reason. I think I'll open up that issue after all!

Thanks for your help!

**Comment by wronk** [comment]
Wasn't able to get reasonable segmentation results with U-net. Closing this for now
