### ISSUE TITLE
Create object detection example

### ISSUE THREAD

**Issue by drewbo** [developmentseed/label-maker#11]

**Comment by Geoyi** [comment]
Object detection and a blog draft work priorities for me this week ;-), @drewbo, and will track the steps here:

- [ ] generate a dataset  from `ml-data-generation`;
- [ ] convert it to Tensorflow API data format tf-records;
- [ ] set up Tensorflow API object detection environment on my `NaNa_ML_Workstation`;
- [ ] set up Inception ResNet model config file. Here we will use Tensorflow’s Faster R-CNN with Inception ResNet instead of MobileNets.  I normally used the later one because it is fastest but the accuracy was compromised even though it was not terrible. Inception ResNet is slower but more accurate than MobileNets;
- [ ] run the model;
- [ ] record the process and thoughts;
- [ ] write a blog draft.

**Comment by drewbo** [comment]
Closed via #30
