### ISSUE TITLE
Error in running label-maker for skynet-train

### ISSUE THREAD

**Issue by emackres** [developmentseed/label-maker#122]
Great to see this new data prep workflow for Skynet. 
https://github.com/developmentseed/label-maker/blob/master/examples/skynet-train-data-prep.md

After using label-maker, I got the [utility script](https://github.com/developmentseed/label-maker/blob/master/examples/utils/skynet.py) to run but got an error:

```
Traceback (most recent call last):
  File "skynet.py", line 24, in <module>
    img = Image.fromarray(label.astype(np.uint8))
  File "/Users/eric/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2431, in fromarray
    size = shape[1], shape[0]
IndexError: tuple index out of range
```

It would be great to know if this is a problem with my setup, or if others are experiencing it and to get it addressed. 

Also, I think there is a typo and the reference to the utility script `python utils/segnet.py` should actually be `python utils/skynet.py`

**Comment by drewbo** [comment]
@emackres thanks for trying it out! Can you post your `config.json` and I'll try to recreate?

**Comment by yulifengwx** [comment]
@drewbo I also got the same error   my config.json like this:
`{
  "country": "togo",
  "bounding_box": [1.09725, 6.05520, 1.34582, 6.30915],
  "zoom": 12,
  "classes": [
    { "name": "Buildings", "filter": ["has", "building"] },
    { "name": "Road", "filter": ["has", "highway"] }
  ],
  "imagery": "http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=access-tocken",
  "background_ratio": 1,
  "ml_type": "classification"
}`
Traceback (most recent call last):
  File "E:/work/AI/label-maker/examples/utils/skynet.py", line 25, in <module>
    img = Image.fromarray(label.astype(np.uint8))
  File "D:\ProgramData\Anaconda3\envs\skynet\lib\site-packages\PIL\Image.py", line 2431, in fromarray
    size = shape[1], shape[0]
IndexError: tuple index out of range
the cause is that the length of label.shape is 1  , in PIL method Image.fromarray  , "size = shape[1], shape[0]"  shape[1] index 1 out of range

**Comment by drewbo** [comment]
@yulifengwx this script is only intended for segmentations labels. Can you try again with the `ml_type` changed to `segmentation`?

**Comment by yulifengwx** [comment]
> @yulifengwx this script is only intended for segmentations labels. Can you try again with the `ml_type` changed to `segmentation`?
@drewbo Thanks for reply ,  set ml_type to segmentation solve the error.  But this is another error when runing with  lastest verison numpy:
 skynet.py in line 34, in keys.remove(key)  ==> 'KeysView' object has no attribute 'remove'. 
with numpy  v1.13.3  the error did not occur.

**Comment by drewbo** [comment]
we're pinned against `v1.13.3` for now but let me know if you can make this work for more recent versions
