### ISSUE TITLE
`labels` subcommand broken by default python

### ISSUE THREAD

**Issue by vpipkt** [developmentseed/label-maker#123]
The `labels` subcommand runs the `stream_filter.py` code as a separate process using the system's default `python`. In my case that was python 2.7 and shapely was not installed so I found this through ImportError. 

In general that is confusing and could lead to incorrect behavior or non-deterministic results. 

https://github.com/developmentseed/label-maker/blob/df0e10e0337ff904bf9e4546598b4c8ba39f5c3c/label_maker/label.py#L79

**Comment by drewbo** [comment]
@vpipkt good find. It's set up in this slightly rickety manner so that we can pipe from `tippecanoe-decode` directly to this function. Do you have an idea of how we can do this natively? We might need to call tippecanoe in a different way but I'm not very familiar with writing Python bindings for C++ libraries; it looks like there are a few examples of python-tippecanoe attempts but nothing very well maintained.

**Comment by vpipkt** [comment]
I have a slightly less rickety idea...

Use [`sys.executable`](https://docs.python.org/3/library/sys.html#sys.executable) in place of `'python'` in the list to `run`. That seems to work with `pip install label-maker`. It recovers the expected interpreter in the shebang line of the `label-maker` script. Which in my case was the same python used to install pip.

Of interest when I was researching this, I found [this footnote](https://docs.python.org/3/tutorial/interpreter.html#id2):

>On Unix, the Python 3.x interpreter is by default not installed with the executable named python, so that it does not conflict with a simultaneously installed Python 2.x executable. 

Given that note an alternative may be to use `'python3.6'`.

**Comment by drewbo** [comment]
@vpipkt you can install from source right now and get this fix or I'll include it in the next release `0.5.2`

**Comment by vpipkt** [comment]
@drewbo thanks much! I used `alternatives` to make sure things ran for me... just include this in the next release!
