### ISSUE TITLE
Filter out cloudy tiles

### ISSUE THREAD

**Issue by giswqs** [developmentseed/label-maker#25]
Using the Vietnam example ("bounding_box": [105.42,20.75,106.41,21.53]), I noticed that there are approximately 200 tiles (out of 2296 downloaded tiles) with very high cloud cover. At least 100 tiles appear to be completely white (100% cloud cover) with the smallest file size (1.7 kb - 3.3 kb). Most image tiles without cloud cover are larger than 5.0 kb. Using these high cloud cover image titles for training could potentially influence the classification accuracy. I know this problem is caused by the Mapbox satellite images, but I was wondering if it could be possible for the label-maker to somehow identify these high cloud cover image tiles and eliminate them from being used for training?

BTW, I trained the Vietnam example on my 64-bit Linux machine (i7-4790 CPU, 32 GB RAM, NVIDIA EVGA GeForce GTX 1050 Ti GPU) using the [resnet.py](https://github.com/developmentseed/label-maker/blob/master/examples/nets/resnet.py) script. The training took approximately 76 minutes. The test accuracy is 83.22%. 

Thank you for developing such a great tool! It makes my life much easier!

**Comment by wronk** [comment]
Hey @giswqs, glad you're finding it useful!

In the short term, you'll probably have to keep removing these by hand maybe (by sorting on file size as you said). You could also try to find a different source of imagery if you have access. I'm not sure if we could automatically detect problems from file size since the same thing will happen for any uniform image (e.g., pure desert, pure grassland, etc.). 

We've toyed with the idea of building an tool to detect (or even segment) clouds in imagery. Unfortunately, I don't think it will happen anytime in the near future though as we're focusing on other features. Sorry I couldn't be more helpful.

**Comment by drewbo** [comment]
@giswqs from our previous work on [skynet-data](https://github.com/developmentseed/skynet-data/) we do have some [scripts for performing similar functions](https://github.com/developmentseed/skynet-data/blob/master/remove-bad-images) (dropping images that have too many light or dark pixels). On a high level, we'd like to incorporate some type of filtering and pre-processing of images in the future. For now you can either manually remove as @wronk suggested or even create a script and run it in-between the `images` and `package` steps

**Comment by giswqs** [comment]
@wronk @drewbo Thank you for your guidance! Appreciated.
