### ISSUE TITLE
Handle human-generated non-OSM labels

### ISSUE THREAD

**Issue by lewfish** [developmentseed/label-maker#32]
I work on [Raster Vision](https://github.com/azavea/raster-vision) at Azavea and this library seems to handle some of the same functionality. We create object detection training chips from GeoTIFFs and human-generated GeoJSON label files, and I'm thinking about how to extend `label-maker` to do this. Do you think this would be in the scope of `label-maker`, or is the focus just on generating labels from OSM data? Handling human-generated label files would make the library more general and usable with pre-existing benchmark datasets, for instance. I saw that there's an issue (#13) for handling GeoTIFFs instead of TMS URLs, which would be step one. The next step would be handling GeoJSON labels, or GeoTIFFs in the case of segmentation. Or maybe the right approach is to convert our data into vector tiles which this library already handles.

**Comment by drewbo** [comment]
@lewfish Raster Vision is great! I haven't checked it out deeply since the [segmentation focus switch](https://github.com/azavea/raster-vision/releases/tag/old-semseg-tagging) but will try to give it a read again soon.

I do think non-OSM labels are within the scope of `label-maker`. Until the tiling scheme is a bit [more flexible](https://github.com/developmentseed/label-maker/issues/31#issuecomment-359916106), it's still easiest to read labels from vector tile sets, so the lowest friction approach right now is to use `tippecanoe` to convert GeoJSON to mbtiles and then run `labels` directly (skipping `download`). There are probably some naming or projection errors that will come up on the first attempts but I'm happy to help debug those and better support this use case going forward.

**Comment by drewbo** [comment]
Closed the wrong issue with my commit

**Comment by giswqs** [comment]
I second this! I would be very nice if label-maker can support custom labels.

**Comment by drewbo** [comment]
Closed via #109
