### ISSUE TITLE
downloading using a COG and download endpoint results in tiles without an extension

### ISSUE THREAD

**Issue by jreiberkyle** [developmentseed/label-maker#80]
I am attempting to use `label-maker images` with a COG download endpoint. The tiles that are downloaded have no extension (and are pretty big). I believe this is due to the COG not being identified as a TIF.

An example of the download endpoint url is:
```
'https://api.planet.com/data/v1/download?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJRanpYU2t0cENBUjJKR0tZQmdXQ0k4SGtKMlkwY3VPTXdtbVNqRW1xQXlxRVBIYmNDZVNPTXBKd3dYQUFFdDF6MENYbng4bVVXMlVUNG1ubmxDUERtdz09IiwiaXRlbV90eXBlX2lkIjoiUFNPcnRob1RpbGUiLCJ0b2tlbl90eXBlIjoidHlwZWQtaXRlbSIsImV4cCI6MTUyNDg3NzIyMiwiaXRlbV9pZCI6Ijc2MDgxOF80ODQ4NzE4XzIwMTctMDktMTdfMGUyZiIsImFzc2V0X3R5cGUiOiJ2aXN1YWwifQ.W1Zcqw4MJ2A5anAuzkYW5UWS0C8jqjccg62YCSj7mjFtGTCCUsMOZ9HxhUxg9_KpLzt8_GGXn0YHdnvCLxqKew'
```

The function determining if an image is TIF ([here](https://github.com/developmentseed/label-maker/blob/master/label_maker/utils.py#L89)) looks at the extension of the `imagery` entry in the config file.  The URL given above, which is the `imagery` entry in my config file, has no extension.v Therefore, the image is not identified as TIF. Because the image is not identified as a TIF, it is downloaded as a TMS ([here](https://github.com/developmentseed/label-maker/blob/master/label_maker/utils.py#L27)), which again looks for an extension (and finds none) and uses that to apply to the downloaded tile.

Is there a way I can force `label-maker images` to download my COG from the endpoint as a TIF?

**Comment by drewbo** [comment]
@jreiberkyle is the url an actual TIF or just an endpoint which downloads the TIF? If it's the latter, I'm not sure that it would work even if it were identified correctly. Probably the easiest way to test is running `rio insp [endpoint]` (since we're using the same loading mechanism).

As for the larger issue (can we identify remote files as valid TIF without using the extension), I'm not too sure but happy for suggestions. We could also include an option to specify the imagery format rather than trying to parse the imagery string extension.

**Comment by jreiberkyle** [comment]
Thanks for the lead @drewbo . The url does actually point to a TIF and `rio insp` does work.

I think providing the option to specify the image format as an optional argument makes sense. For automatic detection, an option is to open with rasterio and look at the driver. Something like this could work:
```
with rasterio.open(geotiff_url) as test_ds:
   if test_ds.meta['driver'] == 'GTiff':
           <open as tiff>
```
